name: deploy.yml
on:
  workflow_run: 
    workflows: ['release.yml']
    types: [completed]
    branches: [master]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Get latest release
        id: get-release
        env:
          GITHUB_REPO: ${{ github.repository }}
          RELEASE_TAG: $(curl -s https://api.github.com/repos/$GITHUB_REPO/releases | jq --raw-output '.[].tag_name')
        run: echo "DOWNLOAD_URL=https://github.com/$GITHUB_REPO/releases/download/$RELEASE_TAG/release.tar.gz" && echo "DOWNLOAD_URL=https://github.com/$GITHUB_REPO/releases/download/$RELEASE_TAG/release.tar.gz" >> "$GITHUB_OUTPUT"
      - name: Download and extract latest release on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            wget ${{ steps.get-release.outputs.DOWNLOAD_URL }} &&
            rm -rf /var/www/* &&
            tar -zxvf release.tar.gz -C /var/www